cask_args appdir: '/Applications'

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

brew "git"
brew "git-lfs"
brew "node"
brew "ruby-build"
brew "tree"
brew "wget"

cask "1password"
cask "1password-cli"
cask "airtable"
cask "arc"
cask "beyond-compare"
cask "brave-browser"
cask "choosy"
cask "docker"
cask "git-credential-manager"
cask "firefox"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive"
cask "istat-menus"
cask "iterm2"
cask "microsoft-office"
cask "microsoft-remote-desktop"
cask "mimestream"
cask "miniconda"
cask "notion-calendar"
cask "onedrive"
cask "parallels"
cask "parallels-toolbox"
cask "postman"
cask "sonos"
cask "spotify"
cask "sublime-text"
cask "visual-studio-code"
cask "whatsapp"
cask "yubico-yubikey-manager"
cask "zoom"
